package com.example.phamvanthinh.solarsystemforchill.GAS;

/**
 * Created by nickpham on 26/08/2016.
 */
public class KhiQuyen {

    String[] KiQuyen = {
            "Nhiệt độ bề mặt của Sao Thủy dao động từ 100 K (-173⁰C) đến 700 K (427⁰C) do sự thiếu vắng bầu khí quyển (khí quyển cực kỳ mỏng) và gradient nhiệt độ biến đổi mạnh giữa xích đạo và các cực. Vùng được Mặt Trời chiếu sáng có nhiệt độ gần 700 K tại điểm cận nhật sau đó giảm xuống 550 K ở điểm viễn nhật. Ở mặt tối của hành tinh này, nhiệt độ trung bình là 110 K. Cường độ bức xạ Mặt Trời trên bề mặt Sao Thủy nằm trong khoảng 4,59 đến 10,61 lần hằng số Mặt Trời (1.370 W•m−2).\n" +
                    "\n" +
                    "Mặc dù nhiệt độ ban ngày trên bề mặt Sao Thủy nhìn chung cực kỳ cao, nhưng các quan sát cho rằng băng (nước) có tồn tại trên Sao Thủy. Đáy của các hố va chạm sâu ở các cực chưa bao giờ tiếp xúc trực tiếp ánh sáng Mặt Trời, và nhiệt độ ở đây duy trì dưới 102 K; rất thấp so với nhiệt độ trung bình của hành tinh này. Băng nước phản xạ rất mạnh với sóng radar, và các quan sát từ kính thiên văn Goldstone đường kính 70 m và VLA trong đầu thập niên 1990 đã tiết lộ rằng có những \"miền\" phản xạ rất mạnh sóng ra đa ở gần các cực. Trong khi băng không phải là nguyên nhân duy nhất gây ra sự phản xạ mạnh ở các vùng này, các nhà thiên văn học tin rằng điều này có khả năng xảy ra rất cao.\n" +
                    "\n" +
                    "Các vùng đóng băng ước lượng chứa khoảng 1014–1015 kg băng, và có thể bị phủ bởi một lớp regolith ức chế sự thăng hoa của chúng. So sánh với các hành tinh khác, các lớp băng ở Nam Cực trên Trái Đất có khối lượng khoảng 4×1018 kg, và chỏm băng ở cực nam của Sao Hỏa chứa khoảng 1016 kg nước. Các nhà khoa học vẫn chưa biết rõ nguồn gốc băng trên Sao Thủy, nhưng hai nguồn có thể xảy ra là từ sự thoát hơi nước trong lòng hành tin hoặc đến từ các sao chổi rơi xuống Sao Thủy.\n" +
                    "\n" +
                    "Với khối lượng quá nhỏ, Sao Thủy không đủ sức bảo tồn bầu khí quyển của nó – các nguyên tử trong bầu khí quyển liên tục bị mất vào trong không gian vì sức hút của trọng lực quá yếu. Hành tinh có một \"tầng khí quyển ngoài\" rất mong manh chứa hiđrô, heli, ôxy, natri, canxi, kali và các nguyên tố khác. Vùng ngoại quyển này không ổn định, các nguyên tử liên tục bị mất và bổ sung từ nhiều nguồn khác nhau. Các nguyên tử hiđrô và heli có thể do gió Mặt Trời mang đến, khuếch tán vào từ quyển của Sao Thủy trước khi thoát trở lại vào không gian. Phân rã phóng xạ của các nguyên tố trong lớp vỏ của Sao Thủy là một nguồn khác cung cấp lượng heli, cũng như natri và kali. MESSENGER đã phát hiện một tỉ lệ lớn các nguyên tố canxi, heli, hydroxit, magiê, ôxy, kali, silic và natri. Hơi nước cũng có mặt, được giải phóng từ nhiều quá trình kết hợp như: sao chổi va quẹt vào bề mặt, hình thành từ sự kết hợp của hiđrô từ gió Mặt Trời và ôxy từ trong đá, và thăng hoa từ các bể băng bị chôn vùi vĩnh cửu trong các hố va chạm tại hai cực tối. Việc phát hiện ra một lượng lớn nước liên quan đến các ion như O+, OH-, và H2O+ là một điều rất ngạc nhiên đối với các nhà khoa học. Do số lượng các ion này xuất hiện trong môi trường không gian quanh Sao Thủy, các nhà khoa học phỏng đoán rằng các phân tử này có thể được thổi đi từ bề mặt hoặc ngoại quyển bởi gió Mặt Trời.\n" +
                    "\n" +
                    "Các nhà khoa học cũng thấy tồn tại natri, kali và canxi trong bầu khí quyển hành tinh vào thập niên 1980-1990, và họ cho đây là kết quả của sự bốc hơi các đá trên bề mặt khi các tiểu thiên thạch va chạm vào Sao Thủy. Năm 2008, thiết bị trên tàu MESSENGER phát hiện ra nguyên tố magiê. Các nghiên cứu chỉ ra rằng, sự phát thải natri xuất hiện ở một số khu vực tương ứng với các cực từ của hành tinh này. Điều này có thể là kết quả của sự tương tác giữa từ quyển và bề mặt của Thủy Tinh.\n" +
                    "\n" +
                    "Ngày 29 tháng 11 năm 2012, NASA công bố xác nhận rằng từ các hình ảnh chụp từ không gian của tàu MESSENGER đã phát hiện các hố va chạm ở cực bắc có chứa băng nước. Sean C. Solomon nới với tờ The New York Times là lượng băng trên Sao Thủy \"đủ để bao phủ Washington, D.C., trong một lớp băng dày hai dặm rưỡi.\"",
            "Sao Kim có khí quyển rất dày, chứa chủ yếu CO2 và lượng nhỏ N2. Khối lượng khí quyển của hành tinh này lớn gấp 93 lần so với khối lượng khí quyển của Trái Đất, trong khi áp suất bề mặt cao gấp 92 so với của Trái Đất—áp này tương đương với độ sâu gần bằng 1 kilômét tính từ bề mặt đại dương trên Trái Đất. Khối lượng riêng/mật độ của không khí tại nơi gần bề mặt bằng 65 kg/m³ (bằng 6,5% của nước). Khí quyển giàu CO2, cùng với đám mây dày SO2, tạo ra hiệu ứng nhà kính mạnh nhất trong các hành tinh trong Hệ Mặt Trời, với nhiệt độ tại bề mặt ít nhất bằng 462 °C. Điều này khiến cho bề mặt của Sao Kim nóng hơn so với của Sao Thủy, với nhiệt độ bề mặt cực tiểu −220 °C và cực đại bằng 420 °C, ngay cả khi khoảng cách từ Sao Kim đến Mặt Trời gần bằng hai lần khoảng cách đó đến Sao Thủy và do vậy hành tinh này chỉ nhận được khoảng 25% năng lượng bức xạ Mặt Trời so với năng lượng Sao Thủy nhận được. Do vậy người ta thường miêu tả bề mặt Sao Kim là địa ngục nóng rực. Nhiệt độ này thậm chí còn cao hơn nhiệt độ cần thiết trong một số quá trình khử trùng.\n" +
                    "\n" +
                    "Nghiên cứu của các nhà khoa học cho thấy hàng tỷ năm trước khí quyển của Sao Kim từng khá giống với khí quyển Trái Đất hơn so với ngày nay, và một số người giả thuyết đã tồn tại nước lỏng trên bề mặt hành tinh, nhưng sau chu kỳ từ 600 triệu đến vài tỷ năm, hiệu ứng nhà kính mất kiểm soát (runaway greenhouse effect) khiến bốc hơi hoàn toàn lượng nước này, và sinh ra lượng khí nhà kính tới mức giới hạn trong bầu khí quyển của nó. Mặc dù những điều kiện vật lý trên hành tinh không còn thích hợp để duy trì những dạng sống nguyên thủy như của Trái Đất nhưng có thể trước đây chúng đã từng tồn tại, và khả năng có những dạng sống bậc thấp tồn tại trong trung tầng và thượng tầng khí quyển vẫn chưa bị bác bỏ.\n" +
                    "\n" +
                    "Quán tính nhiệt (thermal inertia) và sự truyền nhiệt bởi gió trong khí quyển gần bề mặt cho thấy nhiệt độ bề mặt Sao Kim không biến đổi lớn giữa phía ngày và đêm, cho dù hành tinh có tốc độ tự quay cực thấp. Tốc độ gió gần bề mặt là thấp, thổi với vận tốc vài kilômét trên giờ, nhưng do mật độ khí quyển gần bề mặt cao, luồng gió tác động một lực lớn lên những chướng ngại vật nó thổi qua, và vận chuyển bụi và đá nhỏ đi khắp bề mặt hành tinh. Chỉ riêng điều này cũng khiến cho con người đi bộ trên bề mặt hành tinh này cũng rất khó khăn, ngay cả khi nhiệt độ, áp suất và sự thiếu hụt ôxy không còn là một vấn đề.\n" +
                    "\n" +
                    "Bên trên tầng khí quyển CO2 đậm đặc là những lớp mây chứa chủ yếu SO2 và những giọt axít sunfuric. Những đám mây này phản xạ và tán xạ khoảng 90% ánh sáng Mặt Trời đẩy ngược chúng vào không gian vũ trụ, và ngăn cản các nhà khoa học quan sát bề mặt hành tinh này. Các đám mây vĩnh cửu bao phủ toàn bộ Sao Kim có nghĩa rằng mặc dù Sao Kim gần Mặt Trời hơn so với Trái Đất, bề mặt hành tinh không được chiếu sáng nhiều. Những cơn gió mạnh ở những đám mây trên cao với vận tốc 300 km/h có thể thổi đi vòng quanh hành tinh trong thời gian từ bốn đến năm ngày. Những cơn gió trong khí quyển Sao Kim có tốc độ cao gấp 60 lần tốc độ tự quay của hành tinh này, trong khi đó những cơn gió mạnh nhất trên Trái Đất có tốc độ chỉ bằng 10% đến 20% tốc độ tự quay của nó.\n" +
                    "\n" +
                    "Quá trình đẳng nhiệt trong khí quyển Sao Kim rất hữu hiệu; nó duy trì sự không đổi của nhiệt độ khí quyển không những giữa phía ngày và đêm mà còn giữa vùng xích đạo và hai vùng cực. Độ nghiêng trục quay của Sao Kim nhỏ (ít hơn 3 độ, so với 23 độ của Trái Đất) cũng là một nguyên nhân làm sự biến đổi nhiệt độ theo mùa của hành tinh là rất nhỏ. Sự biến đổi rõ rệt của nhiệt độ chỉ xảy ra theo độ cao. Năm 1995, tàu Magellan chụp được ảnh những vùng có độ phản xạ cao tại đỉnh của các ngọn núi cao nhất mà tại những vùng này có phân bố những chất có tính phản xạ như tuyết ở trên Trái Đất. Các nhà khoa học lập luận rằng chất này hình thành trong quá trình tương tự như tuyết, mặc dù trong điều kiện nhiệt độ rất cao. Quá nhiều chất bay hơi ngưng tụ trên gần bề mặt sẽ đẩy khí bay lên và bị lạnh đi hình thành tại những nơi cao hơn, và tại đây chúng lại rơi xuống như mưa. Các nhà khoa học vẫn chưa biết chính xác chất này là gì, nhưng có thể là telua cho tới chì sunfit (galena).\n" +
                    "\n" +
                    "Các đám mây trên Sao Kim cũng phóng tia sét nhiều như trên Trái Đất. Sự tồn tại của sét đã gây tranh cãi khi lần đầu tiên tàu Venera của Liên Xô phát hiện ra những chớp sáng này. Năm 2006–07 tàu Venus Express chụp được rõ ràng sóng electron điện từ, dấu hiệu cho thấy có tia sét. Hình ảnh xuất hiện rời rạc của chúng cho thấy những tia sét này đi kèm với hoạt động của thời tiết. Tốc độ tia sét bằng ít nhất một nửa của nó trên Trái Đất. Năm 2007, tàu Venus Express phát hiện ra hai xoáy khí quyển khổng lồ tồn tại ở cực nam hành tinh.\n" +
                    "\n" +
                    "Một khám phá khác từ tàu Venus Express trong năm 2011 đó là có một tầng ozone ở trên cao khí quyển của Sao Kim.\n" +
                    "\n" +
                    "Ngày 29 tháng 1 năm 2013, các nhà khoa học ESA thông báo tầng điện li của Sao Kim thổi hướng ra ngoài theo cách tương tự như \"đuôi các hạt ion phóng ra từ một sao chổi dưới những điều kiện tương tụ.\"",


            "Áp suất khí quyển trung bình tác dụng lên bề mặt Trái Đất là 101,325 kPa ở độ cao 8,5 km. Không khí chứa 78% nitơ và 21% ôxy, còn lại là hơi nước, điôxít cacbon và các phân tử khí khác. Độ cao của tầng đối lưu thay đổi theo vĩ độ vào khoảng 8 km ở các vùng cực và 17 km ở xích đạo, với các sự thay đổi ảnh hưởng bởi các yếu tố mùa và thời tiết.\n" +
                    "\n" +
                    "Sinh quyển của Trái Đất tạo ra các thay đổi khá lớn đối với bầu khí quyển. Sự quang hợp oxy tiến hóa từ 2,7 tỷ năm trước, tạo ra bầu không khí chứa nitơ-oxy tồn tại ngày nay. Sự thay đổi này tạo điều kiện thuận lợi cho sự phổ biến của các vi sinh vật ưa khí, cũng như việc tầng ôzôn - cùng với từ trường của Trái Đất- đã ngăn chặn các tia phóng xạ, cho phép sự sống tồn tại trên Trái Đất. Các chức năng khác của khí quyển đối với sự sống bao gồm vận chuyển, cung cấp các loại khí hữu dụng, đốt cháy các thiên thạch nhỏ trước khi chúng chạm đất và điều hòa nhiệt độ. Hiện tương cuối cùng được biết dưới cái tên hiệu ứng nhà kính: các phân tử khí thu nhiệt năng tỏa ra từ mặt đất, làm tăng nhiệt độ trung bình. Cacbon dioxit, hơi nước, metan và ozon là các khí nhà kính đầu tiên trong bầu khí quyển của Trái Đất. Nếu không có hiệu ứng duy trì nhiệt này, nhiệt độ trung bình bề mặt sẽ là -18 °C và sự sống sẽ không có khả năng tồn tại.",

            "Sao Hỏa đã mất từ quyển của nó từ 4 tỷ năm trước, do vậy gió Mặt Trời tương tác trực tiếp đến tầng điện li của hành tinh, làm giảm mật độ khí quyển do dần dần tước đi các nguyên tử ở lớp ngoài cùng của bầu khí quyển. Cả hai tàu Mars Global Surveyor và Mars Express đã thu nhận được những hạt bị ion hóa từ khí quyển khi chúng đang thoát vào không gian. So với Trái Đất, khí quyển của Sao Hỏa khá loãng. Áp suất khí quyển tại bề mặt thay đổi từ 30 Pa (0,030 kPa) ở ngọn Olympus Mons tới 1.155 Pa (1,155 kPa) ở lòng chảo Hellas Planitia, và áp suất trung bình bằng 600 Pa (0,600 kPa). Áp suất lớn nhất trên Hỏa Tinh bằng với áp suất ở những điểm có độ cao 35 km trên bề mặt Trái Đất. Con số này nhỏ hơn 1% áp suất trung bình tại bề mặt Trái Đất (101,3 kPa). Tỉ lệ độ cao (scale height) của khí quyển Sao Hỏa bằng 10,8 km, lớn hơn của Trái Đất (bằng 6 km) bởi vì gia tốc hấp dẫn bề mặt Sao Hỏa chỉ bằng 38% của Trái Đất, và nhiệt độ trung bình trong khí quyển Sao Hỏa thấp hơn đồng thời khối lượng trung bình của các phân tử cao hơn 50% so với trên Trái Đất.\n" +
                    "\n" +
                    "Bầu khí quyển Sao Hỏa chứa 95% cacbon điôxít, 3% nitơ, 1,6% argon và chứa dấu vết của ôxy và hơi nước. Khí quyển khá là bụi bặm, chứa các hạt bụi đường kính khoảng 1,5 µm khiến cho bầu trời Sao Hỏa có màu vàng nâu khi đứng nhìn từ bề mặt của nó.\n" +
                    "\n" +
                    "\n" +
                    "Bản đồ mêtan\n" +
                    "Mêtan đã được phát hiện trong khí quyển hành tinh đỏ với tỷ lệ mol vào khoảng 30 ppb; nó xuất hiện theo những luồng mở rộng và ở những vị trí rời rạc khác nhau. Vào giữa mùa hè ở bán cầu bắc, luồng chính chứa tới 19.000 tấn mêtan, và các nhà thiên văn ước lượng cường độ ở nguồn vào khoảng 0,6 kilôgam trên giây. Nghiên cứu cũng cho thấy có hai nguồn chính phát ra mêtan, nguồn thứ nhất gần tọa độ 30° B, 260° T và nguồn hai gần tọa độ 0° B, 310° T. Các nhà khoa học cũng ước lượng được Sao Hỏa sản sinh ra khoảng 270 tấn mêtan trong một năm.\n" +
                    "\n" +
                    "Nghiên cứu cũng chỉ ra khoảng thời gian để lượng mêtan phân hủy có thể dài bằng 4 năm hoặc ngắn bằng 0,6 năm Trái Đất. Sự phân hủy nhanh chóng và lượng mêtan được bổ sung ám chỉ có những nguồn còn hoạt động đang giải phóng lượng khí này. Những hoạt động núi lửa, sao chổi rơi xuống, và khả năng có mặt của các dạng sống vi sinh vật sản sinh ra mêtan. Mêtan cũng có thể sinh ra từ quá trình vô cơ như sự serpentin hóa (serpentinization) với sự tham gia của nước, cacbon điôxít và khoáng vật olivin, nó tồn tại khá phổ biến trên Sao Hỏa.",


            "Sao Mộc cũng có bầu khí quyển lớn nhất trong Hệ Mặt Trời, mở rộng hơn 5000 km theo độ cao. Do Sao Mộc không có bề mặt rắn, đáy của bầu khí quyển được coi là nơi có áp suất khí quyển bằng 10 bar, bằng 10 lần áp suất khí quyển tại bề mặt Trái Đất.\n " +
                    "Sao Mộc bị bao phủ vĩnh cửu các tầng mây chứa tinh thể amoniac và có thể amonium hiđrô sunfit. Các tầng mây nằm ở vị trí biên giới với tầng đối lưu và sắp xếp thành những dải mây khác nhau theo vĩ độ, mà các nhà thiên văn gọi là những \"vùng nhiệt đới\". Những vùng này được chia nhỏ thành những đới (zone) có màu sắc nhẹ và vành đai có màu tối hơn. Sự tương tác giữa những phần hoàn lưu là nguyên nhân hình thành các cơn bão và luồng xoáy. Tốc độ gió cỡ 100 m/s (360 km/h) là thường gặp trong zonal jets. Các nhà khoa học cũng quan sát thấy các biến đổi theo độ rộng, màu sắc và mật độ ở những đới này theo năm, nhưng chúng vẫn có đủ độ ổn định cho phép họ đặt tên phân biệt từng đới.\n" +
                    "\n" +
                    "Tầng mây sâu khoảng 50 km, và chứa ít nhất hai lớp mây: lớp dày và thấp phía dưới cong lớp mỏng ở phía trên. Cũng có những lớp mỏng chứa đám mây nước bên dưới lớp mây amoniac, chúng được phát hiện thông qua ánh chớp tia sét trong khí quyển Sao Mộc. Do nước trong các đám mây có tính phân cực tạo ra hiệu điện thế giữa các đám mây và gây nên sét. Những hiện tượng phóng điện này có thể mạnh gấp hàng nghìn lần tia sét trong khí quyển Trái Đất. Các đám mây nước có thể hình thành theo những cơn bão do luồng nhiệt dâng lên từ phía trong hành tinh. Năm 2013, kính thiên văn không gian Herschel phát hiện ra sự phân bố của nước trong tầng bình lưu tập trung chủ yếu ở bán cầu nam Sao Mộc, và chứng tỏ thuyết phục rằng nước trên hành tinh này có nguồn gốc từ các sao chổi rơi xuống.\n" +
                    "\n" +
                    "Những đám mây có màu vàng và nâu trong khí quyển Sao Mộc là do những hợp chất bay lên cao khi chúng chịu bức xạ tia tử ngoại đến từ Mặt Trời. Các nhà khoa học vẫn chưa biết cơ chế chính xác, nhưng chất cơ bản trong các đám mây này là phốtpho, lưu huỳnh hoặc có thể là các hiđrô cácbon. Những hợp chất màu sắc này, hay nhóm mang màu (chromophore), trộn lẫn vào trong các lớp mây thấp hơn và ấm hơn. Các đới hình thành do những vùng khí đối lưu dâng lên tạo ra hiện tượng tinh thể hóa của amoniac và cản trở các nhà khoa học có thể quan sát những lớp mây ở dưới thấp hơn.\n" +
                    "\n" +
                    "Độ nghiêng trục quay của Sao Mộc khá nhỏ có nghĩa là hai cực của nó không mấy khi nhận được nhiều bức xạ Mặt Trời hơn vùng xích đạo. Nhờ hiện tượng đối lưu xảy ra bên trong hành tinh mà lượng nhiệt nội lực được vận chuyển lên hai vùng cực, giúp cân bằng nhiệt độ giữa các tầng mây. ",

            "Lớp khí quyển bên ngoài của Sao Thổ chứa 96,3% phân tử hiđrô và 3,25% heli. Tỉ lệ heli giảm đáng kể so với sự có mặt của nguyên tố này trong Mặt Trời. Các nhà khoa học vẫn chưa biết chính xác lượng các nguyên tố nặng hơn heli trong khí quyển hành tinh, nhưng họ giả sử rằng tỉ lệ những nguyên tố này bằng với tỷ lệ nguyên thủy của chúng từ lúc hình thành Hệ Mặt Trời. Tổng khối lượng của những nguyên tố nặng này vào khoảng 19–31 lần khối lượng Trái Đất, mà chúng tập trung chủ yếu tại vùng lõi Sao Thổ.\n" +
                    "\n" +
                    "Dấu vết có mặt của các phân tử amoniac, axetylen, êtan, prôpan, phốtphin và mêtan đã được phát hiện ra trong khí quyển của Sao Thổ. Các đám mây trên cao chứa tinh thể amoniac, trong khi những đám mây thấp hơn hoặc là chứa amonium hydrosulfide (NH4SH) hoặc nước. Bức xạ tử ngoại từ Mặt Trời làm cho mêtan bị quang ly trong tầng thượng quyển, dẫn đến một chuỗi các phản ứng hóa học hiđrôcacbon và các sản phẩm rơi xuống dưới sâu bởi những luồng cuộn xoáy và sự khuếch tán trong khí quyển. Chu trình quang hóa này bị chi phối bởi chu kỳ mùa trên Sao Thổ.\n" +
                    "\n",

            "Tuy không có một bề mặt rắn cụ thể trong Sao Thiên Vương, phần bao phủ chứa các khí bên ngoài mà có thể quan trắc từ xa được các nhà khoa học gọi là khí quyển. Khả năng quan trắc từ xa có thể mở rộng sâu xuống dưới 300 km bên dưới mức 1 bar (100 kPa), ở độ sâu có áp suất khoảng 100 bar (10 MPa) và nhiệt độ bằng 320 K. Khí quyển Sao Thiên Vương có một vành nhật hoa mờ nhạt mở rộng ra bên ngoài tới 2 lần bán kính hành tinh tính từ mặt có mức áp suất 1 bar. Các nhà thiên văn chia khí quyển hành tinh này thành 3 tầng: tầng đối lưu, có cao độ từ −300 đến 50 km và áp suất từ 100 giảm đến 0,1 bar; (10 MPa xuống 10 kPa), tầng bình lưu, có cao độ từ 50 đến 4000 km và áp suất trong 0,1 - 10−10 bar (10 kPa giảm đến 10 µPa), và tầng nhiệt/vành nhật hoa mở rộng từ 4.000 km đến khoảng cách 50.000 km tính từ bề mặt hành tinh. Hành tinh này không có tầng trung lưu.",

            "Ở cao độ lớn, khí quyển Sao Hải Vương chứa 80% hiđrô và 19% heli. Cũng có một lượng nhỏ phân tử mêtan. Dấu vết của khí mêtan cũng được phát hiện khi các nhà khoa học quan sát thấy vạch quang phổ hấp thụ điển hình của mêtan ở bước sóng trên 600 nm, trong miền bước sóng đỏ và hồng ngoại. Mêtan trong khí quyển hấp thụ ánh sáng đỏ làm cho Sao Hải Vương hiện lên có màu xanh giống như Sao Thiên Vương. Tuy nhiên, màu xanh da trời sáng của Sao Hải Vương khác hẳn so với màu xanh lơ lạnh của Sao Thiên Vương. Do mật độ mêtan trong khí quyển của hai hành tương tương tự nhau nên người ta chưa biết thành phần nào trong khí quyển là nguyên nhân làm cho hai hành tinh có màu sắc khác nhau.\n" +
                    "\n" +
                    "Khí quyển Sao Hải Vương chia ra thành hai vùng chính; tầng đối lưu phía dưới với nhiệt độ trong tầng này giảm theo cao độ, và tầng bình lưu phía trên với nhiệt độ tăng theo cao độ. Biên giới giữa hai vùng này được gọi là khoảng lặng đối lưu có áp suất là 0,1 bar (10 kPa). Tầng bình lưu chuyển dần thành tầng nhiệt ở áp suất từ 10−5 đến 10−4 microbar (1 đến 10 Pa). Tầng nhiệt chuyển dần sang tầng ngoài nơi tiếp giáp với không gian vũ trụ.\n" +
                    "\n" +
                    "\n" +
                    "Những dải mây ở trên cao phủ bóng xuống tầng mây thấp hơn của Sao Hải Vương. Ảnh của Voyager 2\n" +
                    "Các mô hình khí quyển cho rằng tầng đối lưu của Sao Hải Vương có những dải mây với nhiều thành phần thay đổi phụ thuộc vào cao độ của chúng. Những đám mây cao nhất hình thành ở áp suất dưới 1 bar, nơi nhiệt độ phù hợp cho khí mêtan ngưng tụ. Những vùng có mức áp suất từ 1 đến 5 bar (100 - 500 kPa) có thể hình thành các đám mây amoniac và hiđrô sunfit. Với áp suất trên 5 bar, các đám mây có thể chứa amoniac, amonium sulfide, hiđrô sunfit và nước. Các đám mây băng nước hình thành ở độ sâu với mức áp suất 50 bar (5 MPa), nhiệt độ đạt 0 °C. Bên dưới mức này, cũng có thể có đám mây amoniac và and hiđrô sunfit.\n" +
                    "\n" +
                    "Tàu Voyager 2 đã chụp được ảnh các đám mây ở trên cao khí quyển Sao Hải Vương phủ bóng lên tầng mây mờ bên dưới. Có những dải mây ở độ cao lớn bao xung quanh hành tại một vĩ độ nhất định. Chúng có bề rộng khoảng 50–150 km và cách các tầng mây thấp mờ khoảng 50–110 km.\n" +
                    "\n" +
                    "Quang phổ của Sao Hải Vương cho thấy phía thấp của tầng bình lưu là đám sương mù chứa những phân tử ngưng tụ của quá trình quang ly mêtan, như các sản phẩm êtan và axetylen. Trong tầng bình lưu cũng có dấu vết của phân tử cacbon mônôxít và hidro xyanit. Nhiệt độ của tầng bình lưu trên Sao Hải Vương cao hơn nhiệt độ tầng bình lưu trên Sao Thiên Vương do có nhiều phân tử hiđrôcacbon tập trung hơn.\n" +
                    "\n" +
                    "Tầng nhiệt có nhiệt độ cao bất thường lên tới 750 K do một nguyên nhân chưa rõ. Sao Hải Vương nằm quá xa Mặt Trời để bức xạ tử ngoại từ nó có thể làm nóng tầng này. Một giả thuyết cho cơ chế làm nóng là sự tương tác của các ion trong khí quyển với từ trường của hành tinh. Giả thuyết khác cho rằng sóng trọng lực (gravity wave, chú ý khác với sóng hấp dẫn-gravitational wave) xuất phát từ bên trong hành tinh tiêu tán nhiệt ra khí quyển của nó. Tầng nhiệt chứa lượng nhỏ cacbon điôxít và nước, có nguồn gốc từ bên ngoài như bụi vũ trụ hoặc mảnh vỡ của các thiên thạch."


    };

    public String[] getKiQuyen() {
        return KiQuyen;
    }
}
