package com.example.phamvanthinh.solarsystemforchill.GAS;

/**
 * Created by nickpham on 25/08/2016.
 */
public class PlanetsAOverview {

    public String Mercury = "Sao Thủy hay Thủy Tinh là hành tinh nhỏ nhất và gần Mặt Trời nhất trong tám hành tinh thuộc Hệ Mặt Trời,[a] " +
            "với chu kỳ quỹ đạo bằng 88 ngày Trái Đất. Nhìn từ Trái Đất, hành tinh hiện lên với chu kỳ giao hội trên quỹ " +
            "đạo bằng xấp xỉ 116 ngày, và nhanh hơn hẳn những hành tinh khác. Tốc độ chuyển động nhanh này đã khiến người " +
            "La Mã đặt tên hành tinh là Mercurius, vị thần liên lạc và đưa tin một cách nhanh chóng. Trong thần thoại Hy Lạp " +
            "tên của vị thần này là Hermes (Ερμής). Tên tiếng Việt của hành tinh này dựa theo tên do Trung Quốc đặt," +
            " chọn theo" +
            " hành thủy trong ngũ hành.\n" +
            "\n" +
            "Do hành tinh hầu như không có khí quyển để giữ lại nhiệt lượng," +
            " bề mặt Sao Thủy trải qua sự biến đổi nhiệt độ lớn nhất trong số các hành tinh" +
            ", thay đổi từ 100 K (−173 °C; −280 °F) vào ban đêm tới 700 K (427 °C; 800 °F) vào" +
            " ban ngày. Trục quay của Sao Thủy có độ nghiêng nhỏ nhất trong Hệ Mặt Trời (khoảng 1⁄30 độ), " +
            "nhưng hành tinh lại có độ lệch tâm quỹ đạo lớn nhất.[a] Tại viễn điểm quỹ đạo, Sao Thủy ở cách xa Mặt" +
            " Trời hơn 1,5 so với khi hành tinh ở cận điểm quỹ đạo. Bề mặt hành tinh có rất nhiều hố va chạm nhìn trông" +
            " giống như bề mặt của Mặt Trăng, và hành tinh không còn hoạt động địa chất trong hàng tỷ năm trước.\n" +
            "\n" +
            "Trên Sao Thủy không có sự biến đổi thời tiết theo mùa như ở các hành tinh khác bởi vì nó không có bầu khí" +
            " quyển đáng kể. Hành tinh bị khóa thủy triều với Mặt Trời do đó nó quay trên quỹ đạo rất khác so với các " +
            "hành tinh khác. Khi lấy các ngôi sao cố định làm điểm mốc, nó tự quay được chính xác ba vòng trong hai chu kỳ quỹ đạo quanh Mặt Trời [b]. Khi nhìn từ Mặt Trời, trong hệ quy chiếu quay cùng với chuyển động quỹ đạo, hành tinh hiện lên chỉ quay quanh trục một lần trong hai \"năm\" Sao Thủy. Do vậy nếu có người đứng trên Sao Thủy họ chỉ nhận thấy 1 ngày trong 2 năm.\n" +
            "\n" +
            "Bởi vì quỹ đạo Thủy Tinh nằm bên trong quỹ đạo Trái Đất (và của Sao Kim), khi nhìn từ Trái Đất hành tinh" +
            " có lúc hiện lên vào buổi sáng hoặc vào buổi tối, nhưng không bao giờ có thể nhìn thấy lúc nửa đêm. Tương tự " +
            "như Sao Kim và Mặt Trăng, hành tinh cũng có các pha quan sát khi nó di chuyển trên quỹ đạo. Sao Thủy không có " +
            "một vệ tinh tự nhiên nào. Độ sáng biểu kiến của Sao Thủy thay đổi từ −2,0 đến 5,5; nhưng vì quá gần Mặt Trời " +
            "nên nếu quan sát hành tinh này qua viễn vọng kính rất khó khăn và ít khi thực hiện được.";



    public String getMercury() {
        return Mercury;
    }

    public String Venus = "Sao Kim hay Kim tinh (chữ Hán: 金星), còn gọi là sao Thái Bạch (太白), Thái Bạch Kim tinh (太白金星) (thường dùng khi xem tướng mệnh), là hành tinh thứ hai trong hệ Mặt Trời, tự quay quanh nó với chu kỳ 224,7 ngày Trái Đất.[10] Xếp sau Mặt Trăng, nó là thiên thể tự nhiên sáng nhất trong bầu trời tối, với cấp sao biểu kiến bằng −4.6, đủ sáng để tạo nên bóng trên mặt nước.[12] Bởi vì Sao Kim là hành tinh phía trong tính từ Trái Đất, nó không bao giờ xuất hiện trên bầu trời mà quá xa Mặt Trời: góc ly giác đạt cực đại bằng 47,8°. Sao Kim đạt độ sáng lớn nhất ngay sát thời điểm hoàng hôn hoặc bình minh, do vậy mà dân gian còn gọi là sao Hôm, khi hành tinh này mọc lên lúc hoàng hôn, và sao Mai, khi hành tinh này mọc lên lúc bình minh.\n" +
            "\n" +
            "Sao Kim được xếp vào nhóm hành tinh đất đá và đôi khi người ta còn coi nó là \"hành tinh chị em\" với Trái Đất do kích cỡ, gia tốc hấp dẫn, tham số quỹ đạo gần giống với Trái Đất. Tuy nhiên, người ta đã chỉ ra rằng nó rất khác Trái Đất trên những mặt khác. Sao Kim bị bao bọc bởi lớp mây dày có tính phản xạ cao chứa axít sunfuric, và khiến chúng ta không thể quan sát bề mặt của nó dưới bước sóng ánh sáng khả kiến. Mật độ không khí trong khí quyển của nó lớn nhất trong số bốn hành tinh đất đá, thành phần chủ yếu là cacbon điôxít. Áp suất khí quyển tại bề mặt hành tinh cao gấp 92 lần so với của Trái Đất. Với nhiệt độ bề mặt trung bình bằng 735 K (462 °C), Sao Kim là hành tinh nóng nhất trong Hệ Mặt Trời. Nó không có chu trình cacbon để đưa cacbon trở lại đá và đất trên bề mặt, do vậy không thể có một tổ chức sống hữu cơ nào có thể hấp thụ nó trong sinh khối. Một số nhà khoa học từng cho rằng Sao Kim đã có những đại dương trong quá khứ,[13] nhưng đã bốc hơi khi nhiệt độ hành tinh tăng lên do hiệu ứng nhà kính mất kiểm soát.[14] Nước có thể đã bị quang ly, và bởi vì không có từ quyển hành tinh, hiđrô tự do có thể thoát vào vũ trụ bởi tác động của gió Mặt Trời.[15] Toàn bộ bề mặt của Sao Kim là một hoang mạc khô cằn với đá và bụi và có lẽ vẫn còn núi lửa hoạt động trên hành tinh này.";
    public String getVenus(){
        return Venus;
    }

    public  String Earth = "Trái Đất là hành tinh thứ ba tính từ Mặt Trời, đồng thời cũng là hành tinh lớn nhất trong các hành tinh đất đá của hệ Mặt Trời xét về bán kính, khối lượng và mật độ vật chất. Trái Đất còn được biết tên với các tên Thế giới (World), \"hành tinh xanh\"[note 3] hay \"Địa Cầu\", là nhà của hàng triệu loài sinh vật,[12] trong đó có con người và cho đến nay đây là nơi duy nhất trong vũ trụ được biết đến là có sự sống. Hành tinh này được hình thành cách đây 4,55 tỷ năm[13][14][15][16] và sự sống xuất hiện trên bề mặt của nó khoảng 1 tỷ năm trước. Kể từ đó, sinh quyển, bầu khí quyển của Trái Đất và các điều kiện vô cơ khác đã thay đổi đáng kể, tạo điều kiện thuận lợi cho sự phổ biến của các vi sinh vật ưa khí cũng như sự hình thành của tầng ôzôn-lớp bảo vệ quan trọng, cùng với từ trường của Trái Đất, đã ngăn chặn các bức xạ có hại và chở che cho sự sống.[17] Các đặc điểm vật lý của Trái Đất cũng như lịch sử địa lý hay quỹ đạo, cho phép sự sống tồn tại trong thời gian qua. Người ta hy vọng rằng Trái Đất còn có thể hỗ trợ sự sống thêm 1,5 tỷ năm nữa, trước khi kích thước của Mặt Trời tăng lên và tiêu diệt hết sự sống.[18]\n" +
            "\n" +
            "Bề mặt Trái Đất được chia thành các mảng kiến tạo, chúng di chuyển từ từ trên bề mặt Trái Đất trong hàng triệu năm. Khoảng 71% bề mặt Trái Đất được bao phủ bởi các đại dương nước mặn, phần còn lại là các lục địa và các đảo. Nước là thành phần rất cần thiết cho sự sống và cho đến nay con người vẫn chưa phát hiện thấy sự tồn tại của nó trên bề mặt của bất kì hành tinh nào khác.[note 4][note 5] Tuy nhiên, người ta có chứng cứ xác định nguồn nước có ở Sao Hỏa trong quá khứ, và có thể tồn tại cho tới ngày nay.[19] Lõi của Trái Đất vẫn hoạt động được bao bọc bởi lớp manti rắn dày, lớp lõi ngoài lỏng tạo ra từ trường và lõi sắt trong rắn. Trái Đất là hành tinh duy nhất có sự sống.[22]\n" +
            "\n" +
            "Trái Đất tương tác với các vật thể khác trong không gian bao gồm Mặt Trời và Mặt Trăng. Hiện quãng thời gian Trái Đất di chuyển hết một vòng quanh Mặt Trời bằng 365,26 lần quãng thời gian nó tự quay một vòng quanh trục của mình. Khoảng thời gian này bằng với một năm thiên văn tức 365,26 ngày trong dương lịch.[note 6] Trục tự quay của Trái Đất nghiêng một góc bằng 23,4° so với trục vuông góc với mặt phẳng quỹ đạo,[23] tạo ra sự thay đổi mùa trên bề mặt của Trái Đất trong một năm chí tuyến. Mặt Trăng, vệ tinh tự nhiên duy nhất của Trái Đất, đồng thời cũng là nguyên nhân chính gây ra hiện tượng thủy triều đại dương, bắt đầu quay quanh Trái Đất từ 4,53 tỷ năm trước, vẫn giữ nguyên góc quay ban đầu theo thời gian nhưng đang chuyển động chậm dần lại. Trong khoảng từ 4,1 đến 3,8 tỷ năm trước, sự va đập của các thiên thạch trong suốt thời kì \"Công phá Mạnh muộn\" đã tạo ra những sự thay đổi đáng kể trên bề mặt Mặt Trăng.\n" +
            "\n" +
            "Cả tài nguyên khoáng sản lẫn các sản phẩm của sinh quyển được sử dụng để cung cấp cho cuộc sống của con người. Dân cư được chia thành hơn 200 quốc gia độc lập, có quan hệ với nhau thông qua các hoạt động ngoại giao, du lịch, thương mại, quân sự. Văn hóa loài người đã phát triển tạo nên nhiều cách nhìn về Trái Đất bao gồm việc nhân cách hóa Trái Đất như một vị thần, niềm tin vào một Trái Đất phẳng hoặc một Trái Đất là trung tâm của cả vũ trụ, và một quan điểm nhìn hiện đại hơn như Trái Đất là một môi trường thống nhất cần có sự định hướng.";
    public String getEarth(){
        return Earth;
    }


    public String Jupiter = "Sao Mộc hay Mộc tinh (chữ Hán: 木星) là hành tinh thứ năm tính từ Mặt Trời và là hành tinh lớn nhất trong Hệ Mặt Trời.[12] Nó là hành tinh khí khổng lồ với khối lượng bằng một phần nghìn của Mặt Trời nhưng bằng hai lần rưỡi tổng khối lượng của tất cả các hành tinh khác trong Hệ Mặt Trời cộng lại. Sao Mộc được xếp vào nhóm hành tinh khí khổng lồ cùng với Sao Thổ, (Sao Thiên Vương và Sao Hải Vương được xếp vào hành tinh băng không lồ). Hai hành tinh này đôi khi được gọi là hành tinh kiểu Mộc Tinh hoặc hành tinh vòng ngoài. Các nhà thiên văn học cổ đại đã biết đến hành tinh này,[13] và gắn với thần thoại và niềm tin tôn giáo trong nhiều nền văn hóa. Người La Mã đặt tên hành tinh theo tên của vị thần Jupiter, vị thần quan trọng nhất trong số các vị thần.[14] Tên gọi trong tiếng Trung Quốc, tiếng Triều Tiên, tiếng Nhật và tiếng Việt của hành tinh này được đặt dựa vào hành \"mộc\" trong ngũ hành. Khi nhìn từ Trái Đất, Sao Mộc có cấp sao biểu kiến −2,94, đủ sáng để tạo bóng; và là thiên thể sáng thứ ba trên bầu trời đêm sau Mặt Trăng và Sao Kim. (Sao Hỏa hầu như sáng bằng Sao Mộc khi Sao Hỏa ở những vị trí xung đối trên quỹ đạo của nó với Trái Đất.)\n" +
            "\n" +
            "Sao Mộc chứa chủ yếu hiđrô và heli - chiếm một phần tư khối lượng của nó, mặc dù heli chỉ chiếm một phần mười số lượng phân tử. Có thể có một lõi đá trong hành tinh chứa các nguyên tố nặng hơn,[15] nhưng giống như những hành tinh khí khổng lồ khác, Sao Mộc không có một bề mặt rắn định hình. Bởi vì có tốc độ tự quay nhanh, hình dạng của hành tinh có hình phỏng cầu dẹt (nó hơi phình ra tại xích đạo). Lớp khí quyển ngoài cùng hiện lên với nhiều dải mây ở những độ cao khác nhau, do kết quả của hiện tượng nhiễu loạn khí động và tương tác với những cơn bão tại biên. Một đặc điểm nổi bật trên ảnh chụp của nó đó là Vết Đỏ Lớn, một cơn bão khổng lồ được biết đến tồn tại ít nhất từ thế kỷ 17 khi các nhà thiên văn lần đầu tiên quan sát nó bằng kính thiên văn. Bao quanh Mộc Tinh là một hệ thống vành đai mờ nhạt cũng như từ quyển mạnh. Có ít nhất 67 vệ tinh tự nhiên quay quanh nó, bao gồm bốn vệ tinh lớn nhất gọi là các vệ tinh Galileo do nhà bác học Galileo Galilei lần đầu tiên quan sát năm 1610. Ganymede, vệ tinh lớn nhất, có đường kính lớn hơn Sao Thủy.\n" +
            "\n" +
            "Đã có một vài tàu không gian thám hiểm đến Sao Mộc, bao gồm tàu Pioneer và Voyager trong các phi vụ bay ngang qua và sau đó tàu Galileo bay quay hành tinh này. Con tàu gần đây nhất bay qua Sao Mộc trên hành trình đến Sao Diêm Vương - tàu New Horizons bay qua vào cuối 2007. Con tàu sử dụng sự hỗ trợ của hấp dẫn từ Sao Mộc nhằm tăng tốc độ của nó. Hiện nay tàu Juno của NASA đã đến vào ngày 5 tháng 7 năm 2016.[16][17] Trong tương lai có phi vụ của ESA đến thám hiểm các vệ tinh Galileo nói chung và Europa nói riêng.";
    public String getJupiter(){
        return Jupiter;
    }

    public String Saturn = "Sao Thổ là hành tinh thứ sáu tính theo khoảng cách trung bình từ Mặt Trời và là hành tinh lớn thứ hai về đường kính cũng như khối lượng, sau Sao Mộc trong Hệ Mặt Trời. Tên Sao Thổ hay Thổ Tinh từ Tiếng Trung Quốc 土星 (tǔ xīng) nghĩa là sao đất. Tên tiếng Anh của hành tinh mang tên thần Saturn trong thần thoại La Mã, ký hiệu thiên văn của hành tinh là (♄) thể hiện cái liềm của thần. Sao Thổ là hành tinh khí khổng lồ với bán kính trung bình bằng 9 lần của Trái Đất.[12][13] Tuy khối lượng của hành tinh cao gấp 95 lần khối lượng của Trái Đất nhưng với thể tích lớn hơn 763 lần, khối lượng riêng trung bình của Sao Thổ chỉ bằng một phần tám so với của Trái Đất.[14][15][16]\n" +
            "\n" +
            "Cấu trúc bên trong của Sao Thổ có lẽ bao gồm một lõi sắt, nikel và đá (hợp chất silic và ôxy), bao quanh bởi một lớp dày hiđrô kim loại, một lớp trung gian giữa hiđrô lỏng với heli lỏng và bầu khí quyển bên trên cùng.[17] Hình ảnh hành tinh có màu sắc vàng nhạt là do sự có mặt của các tinh thể amoniac trong tầng thượng quyển. Dòng điện bên trong lớp hiđrô kim loại là nguyên nhân Sao Thổ có một từ trường hành tinh với cường độ hơi yếu hơn so với từ trường của Trái Đất và bằng một phần mười hai so với cường độ từ trường của Sao Mộc.[18] Lớp khí quyển bên trên cùng hành tinh có những màu đồng nhất và hiện lên dường như yên ả so với bầu khí quyển hỗn loạn của Sao Mộc, mặc dù nó cũng có những cơn bão mạnh. Tốc độ gió trên Sao Thổ có thể đạt tới 1.800 km/h, nhanh hơn trên Sao Mộc, nhưng không nhanh bằng tốc độ gió trên Sao Hải Vương.[19][20]\n" +
            "\n" +
            "Sao Thổ có một hệ thống vành đai bao gồm chín vành chính liên tục và ba cung đứt đoạn, chúng chứa chủ yếu hạt băng với lượng nhỏ bụi và đá. Sao Thổ có 62 vệ tinh tự nhiên đã biết[21]; trong đó 53 vệ tinh đã được đặt tên. Số lượng vệ tinh này không bao gồm hàng trăm tiểu vệ tinh (\"moonlet\") bên trong vành đai. Titan là vệ tinh lớn nhất của Sao Thổ và là vệ tinh lớn thứ hai trong Hệ Mặt Trời, nó cũng lớn hơn cả Sao Thủy và là vệ tinh tự nhiên duy nhất trong Hệ Mặt Trời có bầu khí quyển dày đặc.[22]";
    public String getSaturn(){
        return Saturn;
    }

    public String Uranus = "Sao Thiên Vương là hành tinh thứ bảy tính từ Mặt Trời; là hành tinh có bán kính lớn thứ ba và có khối lượng lớn thứ tư trong hệ. Sao Thiên Vương có thành phần tương tự như Sao Hải Vương, và cả hai có thành phần hóa học khác so với hai hành tinh khí khổng lồ lớn hơn là Sao Mộc và Sao Thổ. Vì lý do này, các nhà thiên văn thỉnh thoảng phân chúng vào loại hành tinh khác gọi là \"hành tinh băng khổng lồ\". Khí quyển của Sao Thiên Vương, mặc dù tương tự như của Sao Mộc và Sao Thổ về những thành phần cơ bản như hiđrô và heli, nhưng chúng chứa nhiều \"hợp chất dễ bay hơi\" như nước, amoniac, và mêtan, cùng với lượng nhỏ các hiđrôcacbon.[10] Hành tinh này có bầu khí quyển lạnh nhất trong số các hành tinh trong Hệ Mặt Trời, với nhiệt độ cực tiểu bằng 49 K (−224 °C). Nó có cấu trúc tầng mây phức tạp, với khả năng những đám mây thấp nhất chứa chủ yếu nước, trong khi mêtan lại chiếm chủ yếu trong những tầng mây phía trên.[10] Ngược lại, cấu trúc bên trong Thiên Vương Tinh chỉ chứa chủ yếu một lõi băng và đá.[9]\n" +
            "\n" +
            "Giống như những hành tinh khí khổng lồ khác, Sao Thiên Vương có một hệ thống vành đai, từ quyển, và rất nhiều vệ tinh tự nhiên. Hệ thống Sao Thiên Vương có cấu hình độc nhất bởi vì trục tự quay của hành tinh bị nghiêng rất lớn, gần như song song với mặt phẳng quỹ đạo của hành tinh. Do vậy cực bắc và cực nam của hành tinh này gần như tại vị trí xích đạo so với những hành tinh khác.[14] Năm 1986, những ảnh chụp của tàu không gian Voyager 2 cho thấy Sao Thiên Vương qua ánh sáng khả kiến hiện lên với một màu gần như đồng nhất mà không có các dải mây hay cơn bão như những hành tinh khí khổng lồ khác.[14] Các nhà thiên văn thực hiện quan sát từ mặt đất phát hiện ra dấu hiệu của sự thay đổi mùa và sự gia tăng hoạt động thời tiết trong những năm gần đây khi nó tiếp cận đến vị trí điểm phân trên quỹ đạo. Tốc độ gió trên Sao Thiên Vương đạt tới 250 mét trên giây (900 km/h).[15]";
    public String getUranus(){
        return Uranus;
    }

    public String Neptune = "Sao Hải Vương là hành tinh thứ tám và xa nhất tính từ Mặt Trời trong Hệ Mặt Trời. Nó là hành tinh lớn thứ tư về đường kính và lớn thứ ba về khối lượng. Sao Hải Vương có khối lượng riêng lớn nhất trong số các hành tinh khí trong hệ Mặt trời. Sao Hải Vương có khối lượng gấp 17 lần khối lượng của Trái Đất và hơi lớn hơn khối lượng của Sao Thiên Vương (xấp xỉ bằng 15 lần của Trái Đất).[11] Sao Hải Vương quay trên quỹ đạo quanh Mặt Trời ở khoảng cách trung bình 30,1 AU, bằng khoảng 30 lần khoảng cách Trái Đất - Mặt Trời. Sao Hải Vương được đặt tên theo vị thần biển cả của người La Mã (Neptune). Nó có ký hiệu thiên văn là ♆, là biểu tượng cách điệu cây đinh ba của thần Neptune.\n" +
            "\n" +
            "Sao Hải Vương là hành tinh đầu tiên được tìm thấy bằng tính toán lý thuyết. Dựa vào sự nhiễu loạn bất thường của quỹ đạo Sao Thiên Vương, nhà thiên văn Alexis Bouvard đã kết luận rằng quỹ đạo của nó bị nhiễu loạn do tương tác hấp dẫn với một hành tinh nào đó. Vào ngày 23 tháng 9 năm 1846,[1] nhà thiên văn Johann Galle đã phát hiện ra Sao Hải Vương ở vị trí lệch 1 độ so với tiên đoán của Urbain Le Verrier. Sau đó ít lâu, người ta cũng khám phá ra Triton, vệ tinh lớn nhất của sao Hải Vương, trong khi 13 vệ tinh còn lại của nó chỉ được phát hiện trong thế kỷ 20. Cho tới nay, tàu không gian Voyager 2 là tàu duy nhất bay qua Sao Hải Vương vào ngày 25 tháng 8 năm 1989.\n" +
            "\n" +
            "Sao Hải Vương có cấu tạo tương tự như Sao Thiên Vương, nhưng lại khác biệt với những hành tinh khí khổng lồ như Sao Mộc và Sao Thổ. Khí quyển của sao Hải Vương chứa thành phần cơ bản là hiđrô và heli, cùng một số ít các hiđrôcacbon và có lẽ cả nitơ, tương tự như của Sao Mộc hay Sao Thổ. Tuy nhiên khí quyển của nó chứa tỷ lệ lớn hơn các phân tử \"băng\" như nước, amoniac, và mêtan. Do đó các nhà thiên văn thỉnh thoảng phân loại Sao Thiên Vương và Sao Hải Vương thành các hành tinh băng đá khổng lồ để nhấn mạnh sự khác biệt này.[12] Bên trong Sao Hải Vương chứa chủ yếu băng và đá, giống như Sao Thiên Vương.[13] Lõi hành tinh có thể có bề mặt tuy rắn nhưng nhiệt độ của nó có thể cao tới hàng nghìn độ và áp suất rất lớn.[14] Khí mêtan trong tầng ngoài khí quyển là nguyên nhân Sao Hải Vương hiện lên với màu xanh lam.[15]\n" +
            "\n" +
            "Trái ngược với bầu khí quyển mờ đặc và gần như đồng màu của Sao Thiên Vương, khí quyển của Sao Hải Vương có những vùng hoạt động mạnh và dễ nhận thấy. Năm 1989, tàu Voyager 2 khi bay qua Sao Hải Vương đã chụp được hình ảnh của Vết Tối Lớn trên bán cầu nam có kích thước tương đương với Vết Đỏ Lớn của Sao Mộc. Những vùng hoạt động thời tiết này được duy trì bởi những cơn gió với tốc độ lên tới 2.100 kilômét trên giờ, mạnh nhất trên khí quyển trong các hành tinh thuộc Hệ Mặt Trời.[16] Do cách rất xa Mặt Trời nên lớp khí quyển ngoài cùng của Sao Hải Vương là một trong những nơi lạnh nhất trong Hệ Mặt Trời. Nhiệt độ của những đám mây trên cao khoảng 55 K (-218 °C) trong khi nhiệt độ tại lõi hành tinh xấp xỉ 5.400 K (5.000 °C).[17][18] Sao Hải Vương có một hệ thống vành đai mờ và rời rạc (hay những cung), được phát hiện trong thập niên 1960 nhưng chỉ được xác nhận vào năm 1989 bởi Voyager 2.[19]";
    public String getNeptune(){
        return Neptune;
    }



    public String Mars = "Sao Hỏa còn gọi là: Hỏa Tinh, (Tiếng Anh: Mars) là hành tinh thứ tư tính từ Mặt Trời trong Thái Dương Hệ. Đôi khi hành tinh này còn được gọi tên là Hỏa Tinh. Nó thường được gọi với tên khác là \"Hành tinh Đỏ\", do sắt ôxít có mặt rất nhiều trên bề mặt hành tinh làm cho bề mặt nó hiện lên với màu đỏ đặc trưng.[14] Sao Hỏa là một hành tinh đất đá với một khí quyển mỏng, với những đặc điểm trên bề mặt có nét giống với cả các hố va chạm trên Mặt Trăng và các núi lửa, thung lũng, sa mạc và chỏm băng ở cực trên Trái Đất. Chu kỳ tự quay và sự tuần hoàn của các mùa trên Hỏa Tinh khá giống với của Trái Đất do sự nghiêng của trục quay tạo ra. Trên Sao Hỏa có ngọn núi Olympus Mons, ngọn núi cao nhất trong Hệ Mặt Trời, và hẻm núi Valles Marineris, hẻm núi dài và rộng nhất trong Thái Dương Hệ. Lòng chảo Borealis bằng phẳng trên bán cầu bắc bao phủ tới 40% diện tích bề mặt hành tinh đỏ và có thể là một hố va chạm khổng lồ trong quá khứ.[15][16]\n" +
            "\n" +
            "Cho đến khi tàu Mariner 4 lần đầu tiên bay ngang qua Sao Hỏa vào năm 1965, đã có nhiều suy đoán về sự có mặt của nước lỏng trên bề mặt hành tinh này. Chúng dựa trên những quan sát về sự biến đổi chu kỳ về độ sáng và tối của những nơi trên bề mặt hành tinh, đặc biệt tại những vĩ độ vùng cực, nơi có đặc điểm của biển và lục địa; những đường kẻ sọc dài và tối ban đầu được cho là những kênh tưới tiêu chứa nước lỏng. Những đường sọc thẳng này sau đó được giải thích như là những ảo ảnh quang học, mặc dù các chứng cứ địa chất thu thập bởi các tàu thăm dò không gian cho thấy Sao Hỏa có khả năng đã từng có nước lỏng bao phủ trên diện rộng ở bề mặt của nó.[17] Năm 2005, dữ liệu từ tín hiệu radar cho thấy sự có mặt của một lượng lớn nước đóng băng ở hai cực,[18] và tại các vũng vĩ độ trung bình.[19][20] Robot tự hành Spirit đã lấy được mẫu các hợp chất hóa học chứa phân tử nước vào tháng 3 năm 2007. Tàu đổ bộ Phoenix đã trực tiếp lấy được mẫu nước đóng băng trong lớp đất nông trên bề mặt vào ngày 31 tháng 7 năm 2008.[21]\n" +
            "\n" +
            "Sao Hỏa có hai vệ tinh, Phobos và Deimos, chúng là các vệ tinh nhỏ và dị hình. Đây có thể là các tiểu hành tinh bị Hỏa Tinh bắt được, tương tự như 5261 Eureka-một tiểu hành tinh Trojan của Hỏa Tinh. Hiện nay có ba tàu quỹ đạo còn hoạt động đang bay quanh Sao Hỏa: Mars Odyssey, Mars Express, và Mars Reconnaissance Orbiter. Trên bề mặt nó có robot tự hành thám hiểm Sao Hỏa (Mars Exploration Rover) Opportunity còn hoạt động và cặp song sinh với nó robot tự hành Spirit đã ngừng hoạt động, cùng với đó là những tàu đổ bộ và robot tự hành trong quá khứ-cả thành công lẫn không thành công. Tàu đổ bộ Phoenix đã hoàn thành phi vụ của nó vào năm 2008. Những quan sát bởi tàu quỹ đạo đã ngừng hoạt động của NASA Mars Global Surveyor chỉ ra chứng cứ về sự dịch chuyển thu nhỏ và mở rộng của chỏm băng cực bắc theo các mùa.[22] Tàu quỹ đạo Mars Reconnaissance Orbiter của NASA đã thu nhận được các bức ảnh cho thấy khả năng có nước chảy trong những tháng nóng nhất trên Hỏa Tinh.[23]\n" +
            "\n" +
            "Sao Hỏa có thể dễ dàng nhìn từ Trái Đất bằng mắt thường. Cấp sao biểu kiến của nó đạt giá trị −3,0[7] chỉ đứng sau so với Sao Mộc, Sao Kim, Mặt Trăng, và Mặt Trời.";

    public String getMars() {
        return Mars;
    }


}
